### ISSUE TITLE
Invalid user

### ISSUE THREAD

**Issue by palleerik** [emes30/facebook_messenger#1]
Error 400 : (#100) Ingen matchande användare hittades (Code 100)
No matching user found in english

  - name: messenger
    platform: facebook_messenger
    page_access_token: XXXXX
    targets:
      - sid: xxxxxxxxxxxxx
        name: erik

**Comment by emes30** [comment]
Two kinds of sid are accepted. Phone number in international format starting with `+` sign, or unique user id generated by Facebook. You must create webhook to get your sid, you can't use sid from other chat. Therefore it's easier to use phone number.\
What kind of sid are you using ?

Edit:\
I've just dig into Facebook API and found that you can't use phone number as target until your app is reviewed. You need to grant pages_messaging_phone_number permission.

**Comment by adek1990** [comment]
could you write SID permissions via webhook and how to add permissionsapages_messaging_phone_number to the page?

**Comment by spider7611** [comment]
If not use target get this error:

```
Error setting up platform facebook_messenger
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 71, in async_setup_platform
    notify_service = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/facebook_messenger/notify.py", line 47, in get_service
    config[CONF_PAGE_ACCESS_TOKEN], config[CONF_TARGETS]
KeyError: 'targets'
```

**Comment by spider7611** [comment]
Where can I find the SID?

**Comment by palleerik** [comment]
When trying +46 phone number I get this error "Error 400 : (#100) Param recipient[id] must be a valid ID string (e.g., "123") (Code 100)"

**Comment by emes30** [comment]
I've added instruction in [README](https://github.com/emes30/facebook_messenger/blob/master/README.md#how-to-obtain-your-user-psid), how you can find your user's PSID.

**Comment by adek1990** [comment]
@emes30 Thanks, I'll try to test tomorrow😀

**Comment by Graba994** [comment]
it worked once. The application wrote back my PSID. As my girlfriend wrote, it stopped working.

I generated a new link and VERIFY_TOKEN
But it didn't help

**Comment by emes30** [comment]
First, everyone you want to send messages to must register as facebook developer, then you have to add them as your testers.
![image](https://user-images.githubusercontent.com/35312919/191843100-0b3d93c7-8d2a-4151-b70c-c00d66a40f9a.png)
At your app configuration page click `Roles` and again `Roles`, you'll see `Testers` section. Add your gf there.

**Comment by Graba994** [comment]
the problem is that he doesn't even reply to me anymore :(

**Comment by Graba994** [comment]
@emes30 It's WORK's ! Thanks !

**Comment by spider7611** [comment]
Please help it is not clear for me:

stuck here: 
```
- Paste your Facebook Access Token as PAGE_ACCESS_TOKEN variable value
- Put value of your choice into VERIFY_TOKEN value, exactly the same value you enter at Facebook, step 10
```

I have the generated token (page_access_token) but what is the verify_token?

**Comment by emes30** [comment]
@spider7611 **VERIFY_TOKEN** can be anything, `123456789` will work, it is your secret. It's important to put the same value on both sides (Facebook and Glitch).

**Comment by spider7611** [comment]
Perfect! Thank You!

**Comment by spider7611** [comment]
I'm here again. Added my wife to tester but can't found in her messenger the PSID not found the user.
What is the trick?

**Comment by spider7611** [comment]
> @emes30 It's WORK's ! Thanks !

Hi, Can you help how to get my wife PSID? Registered develepoer and add her to my tester, but not found her messenger my app and can't write a message to receive her PSID. In her developer section my app is there.

**Comment by emes30** [comment]
@spider7611 try to send a message to your wife from your page, when she answers, you'll get the PSID.

**Comment by spider7611** [comment]
@emes30 tryed it, but can only send message to myself. I can search contact but no other people there only me.

**Comment by spider7611** [comment]
Finally I got it. Here is the solution if anybody need it in the future:
So on the created page go to the settings then messages and there find messengeres URL address like this: m.me/3565364365346
This link I sent to my wife on messenger and she opened it and voila she can write a message and get the PSID.

**Comment by bill7531** [comment]
In case anyone else wants to set this up, for users other than the creator, the users need to be signed up as tester as instructed above, which will also require the users to sign up as developers and accept the request. otherwise, the page will not reply with PSID. please consider adding this step in the instruction
